### ISSUE TITLE
ElectronJS Support

### ISSUE THREAD

**Issue by RZEROSTERN** [RZEROSTERN/webpack4-phaser-boilerplate#1]
**Is your feature request related to a problem? Please describe.**
Right now I want to add ElectronJS support to the boilerplate for having the possibility of making **desktop** games based on PhaserJS

**Describe the solution you'd like**
The purpose of this issue is add the support for ElectronJS.

**Additional context**
The most stable pull request wins the approval and the possibility of winning a tee of Hacktoberfest

**Comment by StaniPetrosyan** [comment]
Hello, can I work on this ? 
If I understand, your scope is just add ElectronJS or not ?

**Comment by RZEROSTERN** [comment]
@StaniPetrosyan just add support to ElectronJS, only that. In base to this, I'll release more features/issues to fix

**Comment by RZEROSTERN** [comment]
@StaniPetrosyan if you want to make the feature, feel free to make it 👍

**Comment by RZEROSTERN** [comment]
Closed issue and merged on #2 
Credits for @StaniPetrosyan for making it possible.
